### ISSUE TITLE
Support unmountOnExit

### ISSUE THREAD

**Issue by vincentjames501** [chacestew/react-router-tabs#16]
A feature I love in react bootstrap's tab implementation is the ability to have a component not unmount when a tab is navigated away from (simply hide it). This makes it much easier to restore complex state as we may have some complicated form, google maps, etc in our tabs. It may be out of scope for a project like this, but it would be amazing!

**Comment by chacestew** [comment]
Hey - thanks for the idea.

I think the difference with React-Bootstrap is that it controls the tab contents i.e. it does all the hiding/unhiding or (optionally) mounting/unmounting. This library leaves that up to your `Route` components, and these naturally unmount when the path no longer matches. This is by design and not something you can, or necessarily should, opt out of when using React Router. 

A better solution for persisting state across route-based tabs would be to use a higher state like Redux offers (and [redux-form](https://redux-form.com/) is a good choice for your first example).

**Comment by vincentjames501** [comment]
Yep! I know it's likely out of scope. We do use redux, but if we have several tabs, the tabs container logic begins to be super complicated and responsible for passing down a bunch of props to the child tabs. I.e. we have pages where people can search, paginate, etc and the normal lifecycle is to destroy that state when the component is unmounted vs moving it up to a higher component. It would be cool to have a `<TabRoute>` component wrapper that will mount the component on first match, and only unmount the component when the actual `TabRoute` component is unmounted.

**Comment by chacestew** [comment]
You can use the [children](https://reacttraining.com/react-router/core/api/Route/children-func) prop on your Route components to achieve this (my earlier statement that you can't do this in RR was wrong - sorry!). You'd need to check for the non-existence of a match prop and then render null from inside the component that keeps state - so I don't think we could provide more here. 

If you explore this further and discover other gotchas, please do reopen to share them.
