### ISSUE TITLE
Keep tabs mounted

### ISSUE THREAD

**Issue by HZSamir** [chacestew/react-router-tabs#23]
Hello,
my use-case involves adding a new tab whenever the user visits a new url. The user can also remove each tab individually.
The problem I am facing right now is that I want each tab component to remain **mounted**, assuming there is a form in Tab1, when the user visits Tab2 and goes back to Tab1, he'd expect the form to still be filled with whatever he entered.

So my question is: Is there some way to do this? To keep active tab components mounted and unmount them only when the user manually closes said tab?

Any help at this point would be most helpful.
Thank you.

**Comment by chacestew** [comment]
Hi @Unforgiven-wanda,

What you should be doing in this case is lifting the state of these tabs out of each individual component, so that their state is not lost when they un-mount, and is still available when they are re-mounted. Redux is a common solution to this. You can also simply manage the state in a parent component - this would be good way to try it out before committing to something like Redux. 

As a feature for this library, it would be out of scope.

Hope that provides some guidance.

**Comment by HZSamir** [comment]
Hi, and thank you for the quick answer.
I am considering lifting state to Redux, but so far it seems a bit overkill. Each one of my component is bound to be rather complex, with forms, modals, and an assortment of other states that should preferably remain local. Lifting all of that to Redux, with the bloat of Actions/Reducers that would accompany such a task is daunting honestly.
Alternatively lifting all of the states of the dozens of components I expect to have to a parent component seems just as complicated now.

I am considering ditching React-router entirely and using my own Tab system, as it seems React-router is not exactly suited to my use-case.

I remain open to any suggestions you might have. And thank you for allowing me for bouncing ideas off of you this way.

**Comment by chacestew** [comment]
I agree that react-router may not be the best fit then, as the non-matched routes will always destructively render `null`. Without lifting state, it would be necessary to locate the "hiding" inside your components to make it non-destructive. This is still possible to do with react-router: you can force all your tab routes to match, and then conditionally render inside each tab based on the current `pathname` (or with [useRouteMatch](https://reactrouter.com/web/api/Hooks/useroutematch)). At that point you are half-way toward your own system, but it takes care of the URL state for you.

Whichever path you take, the problem is definitely solvable. Best of luck!

**Comment by HZSamir** [comment]
Many thanks for the pointers, I think I have what I need now.
Have a good day :)
