### ISSUE TITLE
Parameters support

### ISSUE THREAD

**Issue by alexmipego** [chacestew/react-router-tabs#5]
Hello,

I'm at "http://localhost:3000/service/2674d464c64ca745b9e34058" and clicking a tab redirects the browser to "http://localhost:3000/service/:id/admins". Is there are way or trick to ensure the params are correctly passed?

**Comment by chacestew** [comment]
Hi @alexmipego,

I assume your code looks something like this:

```js
<NavTab to="/service/:id/admins" />

<Route path="/service/:id/admins" />
```

But `NavTab` won't work as you expect because the `to` prop does not take regex the same way as the `path` prop. 

The correct way is to reference `match.params.id` which will be available on the currently rendered Route's props, like so:

```js
<NavTab to=`/service/${props.match.params.id}/admins` />
```
Let me know if this works for you. You can also find more detail on RR4's docs for [Route](https://reacttraining.com/react-router/web/api/Route) and [Link](https://reacttraining.com/react-router/web/api/Link).

**Comment by alexmipego** [comment]
Hi,

I've a home.jsx with

```
<Switch>
   <Route path="/service/:id" component={ViewService} />
   <Route component={Dashboard} />
</Switch>
```

and then a "ViewService" component with:

```
<RoutedTabs startPathWith={match.path} className="panel-header">
   <NavTab to="/admins">Admins</NavTab>
   <NavTab to="/service/:id/admins">Moderators</NavTab>
   <NavTab to="/service/${props.match.params.id}/admins">Users</NavTab>
</RoutedTabs>
```

In every of those 3 tab cases, the url is literal, e.g. the last tab redirect the browser to "http://localhost:3000/service/:id/service/$%7Bprops.match.params.id%7D/admins".

I maybe missing some "basic" react or meteorJS detail here...

**Comment by alexmipego** [comment]
Got it. Needed to update startPathWith to startPathWith={\`${match.params.id}\`}.

**Comment by chacestew** [comment]
Just fyi, I wouldn't recommend using `startPathWith` for this case. Your only issue above was using string literal `" "` instead of a template string ``` ` ` ```.
